apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-1"
  namespace: "default"
  labels:
    app: "nginx-2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nginx-2"
  template:
    metadata:
      labels:
        app: "nginx-2"
    spec:
      containers:
      - name: "nginx-infected-1"
        image: "cacheattack.azurecr.io/cacheattack/nginx_infected:1.20.1-14"
        command: ["tail"]
        args: ["-f", "/dev/null"]
      - name: "nginx-infected-2"
        image: "cacheattack.azurecr.io/cacheattack/nginx_infected:1.20.1-14"
        command: ["tail"]
        args: ["-f", "/dev/null"]
